[build]
base = "sustainable-development-goals-visualiser/"
publish = "sustainable-development-goals-visualiser/build/"
command = "yarn build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
